config/routes.rb
Rails.application.routes.draw do
  get 'charges/create'
  get 'charges/new'
  resources :charges
  post 'add_to_cart' => 'carts#add_to_cart'
  get 'view_order' =>'carts#view_order'
  get 'checkout' =>'carts#checkout'
  get 'storefront/all_items'
  get 'storefront/items_by_category'
  get 'storefront/items_by_brand'
  root 'storefront#all_items'
  devise_for :users
  resources :products
  post 'order_complete' => 'carts#order_complete'
  get 'categorical' => 'storefront#items_by_category'
  get 'branding' => 'storefront#items_by_brand'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
end

app/models/line_item.rb
class LineItem < ApplicationRecord
	belongs_to :product 
	belongs_to :order, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :line_items
	belongs_to :user, optional: true
	serialize :order_items, Hash
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :categories,:brands, :authenticate_user!


	def categories
	 @categories = Category.order(:name)
	end
	def brands
	 @brands = Product.pluck(:brand).sort.uniq
	end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, except: [:add_to_cart, :view_order]
  
  def add_to_cart
  	 line_item = LineItem.create(product_id: params[:product_id], quantity: params[:quantity])
  	 line_item.update(line_item_total: (line_item.quantity * line_item.product.price))
	  redirect_back(fallback_location: root_path)
  end

  def view_order
  	@line_items = LineItem.all
  end
  def order_complete
  	@order = Order.find(params[:order_id]) #select * from Order where id =
    @amount = (@order.grand_total.to_f.round(2) * 100).to_i

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Rails Stripe customer',
      :currency => 'usd'
    )

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to cart_path
  end

	def checkout
  line_items = LineItem.all
  @order = Order.create(user_id: current_user.id, sub_total: 0)

  line_items.each do |line_item|
    line_item.product.update(quantity: (line_item.product.quantity - line_item.quantity))
    @order.order_items[line_item.product_id] = line_item.quantity 
    @order.sub_total += line_item.line_item_total
  end
  @order.save

  @order.update(sales_tax: (@order.sub_total * 0.08))
  @order.update(grand_total: (@order.sales_tax + @order.sub_total))

  line_items.destroy_all
end

end

app/controllers/charges_controller.rb
# charges_controller.rb
class ChargesController < ApplicationController

  def new
    # view houses a form,
    # nothing for us to do here!
  end

  def create
    # this action is what actually performs the transaction.
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => 'salazar.carlosno9@gmail.com',
      :card => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Rails Stripe customer',
      :currency => 'usd'
    )

    rescue Stripe::CardError => e
    flash[:error] = e.message
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name,:image, :price, :quantity, :description, :brand, :rating, :category_id)
    end
end

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController
  def all_items
  	@products = Product.all #Select * from product" 
  end

  def items_by_category
  	@products = Product.where(category_id: params[:category_id]) 
  	#select products where category_id = 4
	  @category = Category.find(params[:category_id])
	 #select Category where category id = 4
  end

  def items_by_brand
    @products = Product.where(brand: params[:brand])
    @brand = params[:brand] 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/carts/add_to_cart.html.erb
def add_to_cart
    #create an order earlier using our helper method
    @order = current_order
    # get all the items from our line_item table
    line_item = @order.line_items.find_by(product_id: params[:product_id])
  
    #check to see if product already exists in our cart to prevent doubles
      if !line_item.blank?
         line_item.update(quantity: line_item.quantity += params[:quantity].to_i)
         line_item.update(line_item_total: line_item.quantity * line_item.product.price)

      else
        #if the item is already in the cart, update the quantity	
        line_item = @order.line_items.new(product_id: params[:product_id], quantity: params[:quantity])
        
        @order.save
        session[:order_id] = @order.id
        line_item.update(line_item_total: (line_item.quantity * line_item.product.price))

      end
    redirect_back(fallback_location: root_path)
  end

app/views/carts/checkout.html.erb
<h2>Thanks for shopping with us!</h2>
<p>Let's review your order:</p>

<% @order.order_items.each do |k,v| %>
  <ul>
    <li><%= Product.find(k).name %>, <%= v %></li>
  </ul>
<% end %>

<p>
  <strong>Subtotal: </strong><%= number_to_currency @order.sub_total %> 
</p>

<p>
  <strong>Sales Tax: </strong><%= number_to_currency @order.sales_tax %> 
</p>

<p>
  <strong>Order Total: </strong><%= number_to_currency @order.grand_total %> 
</p>
<div>
  <%= form_tag order_complete_path do %>
    <article>
      <label class="amount">
        <span><%= number_to_currency @order.grand_total %></span>
      </label>
    </article>
    <div>
      <%= hidden_field_tag :order_id, @order.id %>
     
    </div>

    <script src="http://checkout.stripe.com/checkout.js"
    class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="Order #<%= @order.id %>"
    data-amount="<%= (@order.grand_total.to_f.round(2) * 100) %>"></script>
  <% end %>
</div>

app/views/carts/order_complete.html.erb
<h2>Thank you for your order!</h2>

<p>
  Order #<%= @order.id %> will be shipping to you, 
  <%= @order.user.email %>, as soon as possible!
</p>

app/views/carts/view_order.html.erb
<h2>My Cart</h2>

<div>
  <% @line_items.each do |line_item| %>
    <li><%= line_item.product.name %></li>
    <li><%= number_to_currency line_item.product.price %></li>
    <li>Qty: <%= line_item.quantity %></li> 
    <li>Subtotal: <%= number_to_currency line_item.line_item_total %></li>
  <% end %>
</div>

<div>
  <%= link_to "Proceed to Checkout?", checkout_path, class: "btn btn-success" %>
</div>

app/views/charges/create.html.erb
<!-- create.html.erb -->
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<!-- new.html.erb -->
<div>
  <%= form_tag charges_path do %>
    
    <article>
      <label class="amount">
        <span>Amount: $5.00</span>
      </label>
    </article>
    
    <script src="https://checkout.stripe.com/checkout.js" 
    class="stripe-button" 
    data-key="<%=Rails.configuration.stripe[:publishable_key] %>" 
    data-description="A month's subscription" 
    data-amount="500"></script>
    
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcommerceFt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
      <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">WebSiteName</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="<%=root_path%>">Home</a></li>
         
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% @categories.each do |category| %>
                <li><%= link_to category.name, categorical_path(category_id: category.id) %></li>
              <% end %>
            </ul>
          </li>

          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% @brands.each do |brand| %>
                <li><%= link_to brand, branding_path(brand: brand) %></li>
              <% end %>
            </ul>
          </li>


      </ul>
      <ul class="nav navbar-nav navbar-right">
          
           <li>
            <%= link_to "View Cart", view_order_path %>             
            </li>
            <% if user_signed_in? %>
              <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello, <%= current_user.email %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Edit Profile", edit_user_registration_path %>
                  </li>
                  <li>                     
                    <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Sign In", new_user_session_path %></li>
            <% end %>  
      </ul>             
      </div>
      </div>
      </nav>  
      <div class="container">   
      <%= yield %> 
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="form-group">
        <strong>Upload Product Image:</strong>
        <%= form.file_field :image %>
  </div>
  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="form-group">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="form-group">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="form-group">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="form-group">
    <label>Product Category
    <%= form.select :category_id, @categories.collect{ |c|[c.name, c.id] },{include: "Select Category"} %>
    </label>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Description</th>
      <th>Brand</th>
      <th>Rating</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= number_to_currency product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= product.description %></td>
        <td><%= product.brand %></td>
        <td><%= product.rating %></td>
        <td><%= product.category_id %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1> Product Item</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>
<p>
  
  <% if @product.image.url.nil? == false %>
  <%= image_tag @product.image_url, alt: "product image" %>
  <% end %>
</p>
<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @product.rating %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/storefront/all_items.html.erb
<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-4">
      <div class="well">
        <% if product.image.url.nil? == false %>
          <p><%= image_tag product.image.url ,class:"img-thumbnail" %></p>
        <% end %>
        <h3><%= link_to product.name, product %></h3>
        <p><%= number_to_currency product.price %></p>
        <p>
          <a href="#" data-toggle="modal" data-target="#myModal_<%= product.id %>">
            <span class="glyphicon glyphicon-plus"></span> Quick Info
          </a>
        </p>
      </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="myModal_<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            <h4 class="modal-title" id="myModalLabel">
              <%= product.name %>    
            </h4>
          </div>
          <div class="modal-body">
            <% if product.image.url.nil? == false %>
            <p><%= image_tag product.image.url, class: "storefront-pics" %></p>
            <% end %>
            <h3><%= link_to product.name, product %></h3>
            <p><%= number_to_currency product.price %></p>
            <p>made by <%= product.brand %></p>       </div>
            <div class="modal-footer">
            <p>
            <%= form_tag add_to_cart_path do %>
              <%= hidden_field_tag :product_id, product.id %>
              <label>How many? <%= number_field_tag :quantity, 1  %></label>
              <%= submit_tag "Add to Cart", class: "btn btn-primary" %>
            <% end %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/storefront/items_by_brand.html.erb
<h1>Here are our <%= @brand %> products</h1>
<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-4">
      <div class="well center-it">
        <p><%= image_tag product.image.url %></p>
        <h3><%= link_to product.name, product %></h3>
        <p><%= number_to_currency product.price %></p>
        <p>
          <a href='#' data-toggle="modal" data-target="#myModal_<%= product.id %>">
            <span class='glyphicon glyphicon-plus'></span>More Info
          </a>
        </p>
      </div>
    </div>


    <!-- Modal -->
    <div class="modal fade" id="myModal_<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            <h4 class="modal-title" id="myModalLabel"><%= product.name%></h4>
          </div>
          <div class="modal-body">
            <p><%= image_tag product.image.url %></p>
            <p><%= number_to_currency product.price %></p>
            <p><%= product.description %></p>
          </div>
          <div class="modal-footer">
            <p>
              <%= form_tag add_to_cart_path do %>
                <%= hidden_field_tag :product_id, product.id %>
               <label>How many? <%= number_field_tag :quantity, 1 %></label>
                <%= submit_tag "Add to Cart", class: "btn btn-primary" %>
              <% end %>
            </p>
          </div>
        </div>
      </div>
    </div>

  <% end %>
</div>

app/views/storefront/items_by_category.html.erb
<h1>All of our <%= @category.name %></h1>
<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-4">
      <div class="well">
        <% if product.image.url.nil? == false %>
          <p><%= image_tag product.image.url ,class:"img-thumbnail" %></p>
        <% end %>
        <h3><%= link_to product.name, product %></h3>
        <p><%= number_to_currency product.price %></p>
        <p>
          <a href="#" data-toggle="modal" data-target="#myModal_<%= product.id %>">
            <span class="glyphicon glyphicon-plus"></span> Quick Info
          </a>
        </p>
      </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="myModal_<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            <h4 class="modal-title" id="myModalLabel"><%= product.name%></h4>
          </div>
          <div class="modal-body">
            <p><%= image_tag product.image.url %></p>
            <p><%= number_to_currency product.price %></p>
            <p><%= product.description %></p>
          </div>
          <div class="modal-footer">
            <p>
              <%= form_tag add_to_cart_path do %>
                <%= hidden_field_tag :product_id, product.id %>
               <label>How many? <%= number_field_tag :quantity, 1 %></label>
                <%= submit_tag "Add to Cart", class: "btn btn-primary" %>
              <% end %>
            </p>
          </div>
        </div>
      </div>
    </div>

 <% end %>
</div>